# Generated by Django 5.1.7 on 2025-11-22 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('title_fr', models.CharField(max_length=200, verbose_name='Title (French)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_fr', models.TextField(verbose_name='Description (French)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company Value',
                'verbose_name_plural': 'Company Values',
                'ordering': ['order', 'title_fr'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('project_type', models.CharField(choices=[('interior', 'Interior Joinery'), ('cabinetry', 'Cabinetmaking'), ('restoration', 'Restoration'), ('fitting', 'Fitting'), ('other', 'Other')], max_length=20)),
                ('budget', models.CharField(blank=True, choices=[('< 5000', '< 5,000 €'), ('5000-15000', '5,000 - 15,000 €'), ('> 15000', '> 15,000 €')], max_length=20)),
                ('description', models.TextField()),
                ('files', models.JSONField(blank=True, default=list, help_text='List of uploaded file URLs')),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_fr', models.CharField(max_length=300, verbose_name='Question (French)')),
                ('question_en', models.CharField(max_length=300, verbose_name='Question (English)')),
                ('answer_fr', models.TextField(verbose_name='Answer (French)')),
                ('answer_en', models.TextField(verbose_name='Answer (English)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'question_fr'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('title_fr', models.CharField(max_length=200, verbose_name='Title (French)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('category', models.CharField(choices=[('kitchen', 'Kitchen'), ('living', 'Living Room'), ('exterior', 'Exterior')], max_length=20)),
                ('type', models.CharField(choices=[('creation', 'Creation'), ('restoration', 'Restoration'), ('fitting', 'Fitting')], max_length=20)),
                ('material', models.CharField(choices=[('oak', 'Oak'), ('walnut', 'Walnut'), ('maple', 'Maple')], max_length=20)),
                ('short_desc_fr', models.TextField(verbose_name='Short Description (French)')),
                ('short_desc_en', models.TextField(verbose_name='Short Description (English)')),
                ('full_desc_fr', models.TextField(verbose_name='Full Description (French)')),
                ('full_desc_en', models.TextField(verbose_name='Full Description (English)')),
                ('challenge_fr', models.TextField(blank=True, verbose_name='Challenge (French)')),
                ('challenge_en', models.TextField(blank=True, verbose_name='Challenge (English)')),
                ('duration_fr', models.CharField(blank=True, max_length=100, verbose_name='Duration (French)')),
                ('duration_en', models.CharField(blank=True, max_length=100, verbose_name='Duration (English)')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('finish_fr', models.CharField(blank=True, max_length=100, verbose_name='Finish (French)')),
                ('finish_en', models.CharField(blank=True, max_length=100, verbose_name='Finish (English)')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('featured', models.BooleanField(default=False, help_text='Display on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('service_id', models.CharField(help_text="Unique identifier (e.g., 'interior')", max_length=50, unique=True)),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('title_fr', models.CharField(max_length=200, verbose_name='Title (French)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_fr', models.TextField(verbose_name='Description (French)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('sub_services', models.JSONField(blank=True, default=list, help_text='List of sub-services (bilingual)')),
                ('process_steps', models.JSONField(blank=True, default=list, help_text='Process steps (bilingual)')),
                ('timeframe_fr', models.CharField(blank=True, max_length=100, verbose_name='Timeframe (French)')),
                ('timeframe_en', models.CharField(blank=True, max_length=100, verbose_name='Timeframe (English)')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'service_id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_fr', models.CharField(max_length=200, verbose_name='Role (French)')),
                ('role_en', models.CharField(max_length=200, verbose_name='Role (English)')),
                ('experience_years', models.IntegerField(default=0, help_text='Years of experience')),
                ('quote_fr', models.TextField(verbose_name='Quote (French)')),
                ('quote_en', models.TextField(verbose_name='Quote (English)')),
                ('image', models.URLField(blank=True, help_text='URL to team member photo')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('stars', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('image', models.URLField(blank=True, help_text='URL to client photo')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title_fr', models.CharField(max_length=200, verbose_name='Title (French)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_fr', models.TextField(verbose_name='Description (French)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['year', 'order'],
            },
        ),
    ]
