# Generated by Django 5.2.14 on 2026-05-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_contactsubmission_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
